### ISSUE TITLE
Load IPAdapter Model node stopped working 

### ISSUE THREAD

**Issue by NeoAnthropocene** [cubiq/ComfyUI_IPAdapter_plus#249]
After the last update the `Load IPAdapter Model` node stopped listing models.
Does anyone have the same problem?

![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/112825147/3a434b5c-3f3d-4d59-bd61-f1c0be63b200)
![image](https://github.com/cubiq/ComfyUI_IPAdapter_plus/assets/112825147/f3d054d9-da94-4c0f-9028-3c2474356a21)

ComfyUI: 1931[89507f](2024-01-25)
Manager: V2.4.1

**Comment by 0s0ng** [comment]
Load CLIP Vision is undefined for me

**Comment by cardenluo** [comment]
me too

**Comment by cardenluo** [comment]
change the name "ComfyUI\models\IPAdapter_plus_models"   ,  to   "ComfyUI\models\IPAdapter"
it's work for me.

**Comment by NeoAnthropocene** [comment]
OK, my problem solved when I added an extra `ipadapter` index under my `extra_model_paths.yaml` file under the ComfyUI folder.
Previously it was working without this line. But It works again with this way :)

If you are calling the models, controlnets and other stuff from A1111 folder, just add a lign for ipadapter. And close/open the terminal. That should solve your problem. 

My current `extra_model_paths.yaml` file is like this:
```
#Rename this to extra_model_paths.yaml and ComfyUI will load it

#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
a111:
    base_path: [YOUR A1111 FOLDER PATH HERE]

    checkpoints: models/Stable-diffusion
    configs: models/Stable-diffusion
    vae: models/VAE
    loras: |
         models/Lora
         models/LyCORIS
    upscale_models: |
                  models/ESRGAN
                  models/RealESRGAN
                  models/SwinIR
    embeddings: embeddings
    hypernetworks: models/hypernetworks
    controlnet: |
            models/ControlNet
            extensions/sd-webui-controlnet/models
    ipadapter: extensions/sd-webui-controlnet/models
#other_ui:
#    base_path: path/to/ui
#    checkpoints: models/checkpoints
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes
```
