### ISSUE TITLE
Models not loaded from extra_model_paths.yaml

### ISSUE THREAD

**Issue by TrevorSquillario** [cubiq/ComfyUI_IPAdapter_plus#766]
ipadapter models aren't loaded from `extra_model_paths.yaml`. Only when symlink the model from /models/ipadapter to /app/models/ipadapter it works

Seems to track back to this PR not being merged https://github.com/comfyanonymous/ComfyUI/pull/3299

```
comfyui:
#     base_path: path/to/comfyui/
#     # You can use is_default to mark that these folders should be listed first, and used as the default dirs for eg downloads
  is_default: true
  checkpoints: /models/checkpoints/
  clip: /models/clip/
  clip_vision: /models/clip_vision/
  configs: /models/configs/
  controlnet: /models/controlnet/
  diffusion_models: |
               /models/diffusion_models
               /models/unet
  embeddings: /models/embeddings/
  loras: /models/loras/
  upscale_models: /models/upscale_models/
  vae: /models/vae/
  animatediff_models: /models/animatediff_models/
  animatediff_motion_lora: /models/animatediff_motion_lora/
  ipadapter: /models/ipadapter/
  clip: /models/clip/
  clip_vision: /models/clip_vision/
```

![image](https://github.com/user-attachments/assets/46b4e412-1b6f-48c9-b180-20ae55983d80)

```
kohya@3aac82965fa8:/app/models/ipadapter$ ll /models/ipadapter/
total 191776
drwxrwxr-x  2 1000 1000     4096 Dec 16 08:58 ./
drwxr-xr-x 12 root root     4096 Dec 16 22:19 ../
-rwxrwxr-x  1 1000 1000 98183288 Apr 23  2024 ip-adapter-plus_sd15.safetensors*
-rwxrwxr-x  1 1000 1000 98183728 Mar 17  2024 ip_plus_composition_sd15.safetensors*
kohya@3aac82965fa8:/app/models/ipadapter$ ln -s /models/ipadapter/ip-adapter-plus_sd15.safetensors .
kohya@3aac82965fa8:/app/models/ipadapter$ ll
total 8
drwxr-sr-x  2 kohya root 4096 Dec 16 22:23 ./
drwxr-sr-x 23 kohya root 4096 Dec 16 22:23 ../
lrwxrwxrwx  1 kohya root   50 Dec 16 22:23 ip-adapter-plus_sd15.safetensors -> /models/ipadapter/ip-adapter-plus_sd15.safetensors*
```

![image](https://github.com/user-attachments/assets/90d9b1c9-f2da-410d-ba82-795309652837)

docker-compose.yaml

```
  comfyui-rocm:
    build: 
      context: .
      dockerfile: build/Dockerfile.comfyui.rocm
    container_name: comfyui-rocm
    command: python main.py --listen 0.0.0.0
    user: kohya
    environment:
      TZ: "Asia/Jakarta"
      ROC_ENABLE_PRE_VEGA: 1
    ports:
      - "8188:8188"
    devices:
      - "/dev/kfd:/dev/kfd"
      - "/dev/dri:/dev/dri"
    group_add:
      - video
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    volumes:
      - /data/app/comfyui:/app
      - /data/models/Stable-diffusion:/models/checkpoints/Stable-diffusion
      - /data/models/Stable-diffusion:/models/animatediff_models
      - /data/models/ESRGAN:/models/upscale_models
      - /data/models/LoRA:/models/loras
      - /data/models/LoRA:/models/animatediff_motion_lora
      - /data/models/VAE:/models/vae
      - /data/models/ControlNet:/models/controlnet
      - /data/models/IPAdapter:/models/ipadapter
      - /data/models/CLIP:/models/clip
      - /data/models/CLIPVision:/models/clip_vision
```
